

main:
	g++ -g udp_streamer.cc -Wall -o udp -I /usr/include/opencv4 -I ./sockpp/include -I ./raspicam-0.1.9/src/ -L /usr/lib/arm-linux-gnueabih/ -L ./ -lopencv_videoio -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lraspicam -lraspicam_cv -lstdc++ -lsockpp 